version: '3'

tasks:
  dist:
    cmds:
      - cp _site/* docs

  watch:
    cmds:
      - watchexec -e vto,css deno task build

  minify:
    cmds:
      - minify -w -o src/static/cv.min.css src/static/cv.css
